### PR TITLE
Update soccer example package

### PR DESCRIPTION
**Pull request by jimmyDunne**
PR updates the Soccer Kick package to work with 4.0. Includes CMake addition that will include the soccer kick example in the distribution.

### CODE REVIEW

**Comment by jimmyDunne** [comment]
Images of the current updates

image

image

Immediately after running script for the first time (notice the Parameters Window tab)

image

After adjusting the  tab windows

image

**Comment by jenhicks** [comment]
Fixes #2024

**Comment by jimmyDunne** [comment]
@aymanhab this should be ready for review. I have distributed the Model and Geometry in the Models/SoccerKick dir and the remaining files in Tutorials/Soccer_Kick. I locally tested the Cmake install and everything seemed to work well.

**Comment by aymanhab** [comment]
LGTM, feel free to merge. The ball display is messed up due to having 2 pieces of coincident geometry that get resolved arbitrarily as you zoom out (z-fighting). Open a separate issue on that and we can solve by tweaking the geometry or associating a map with a solid sphere.

**Pull request merged**
