### PR TITLE
Convert all binary vtp files to ascii vtp

### LINKED ISSUE #38: Convert binary .vtp files to ascii format for all models
From [opensim-core closed issue #1976](https://github.com/opensim-org/opensim-core/issues/1976) 

Example models (Rajagopal2015, Hamner2010).

@tkuchida commented on Sat Aug 05 2017

Where possible, we should replace binary vtp files with geometry that can be loaded, particularly for these popular models. Sports.osim is another example (mentioned in #334).

@chrisdembia commented on Thu Aug 31 2017

Python script to convert file formats with VTP: https://gist.github.com/thomasballinger/1281457

### PR DESCRIPTION
**Pull request by chrisdembia**
Fixes #38. I used the script `vtpbinary2ascii.py` that I added to the Geometry folder. I confirmed that I could get `hat_ribs_scap.vtp` to show in the 4.0 GUI.

### CODE REVIEW

**Comment by chrisdembia** [comment]
The failed builds can be ignored.

**Comment by aymanhab** [comment]
Can you take a look @tkuchida @aseth1 or @jimmyDunne  Should be quick review since it's just replacing files in one format with another

**Comment by tkuchida** [comment]
I presume the test involves loading the model in the latest 4.0 GUI build and comparing to 3.3. Which models are affected?

**Comment by chrisdembia** [comment]
> Which models are affected?

- Sky.vtp: SockerKickingModel.osim
- linkage1.vtp: bouncing_block.osim and bouncing_block_weak_spring.osim
- hat_ribs_scap.vtp: SockerKickingModel.osim
- big_block_centered.vtp: bouncing_block.osim and bouncing_block_weak_spring.osim

The other vtp files are not used by models in the Models folder of this repo.

**Comment by tkuchida** [comment]
I downloaded the latest GUI beta (OpenSim-4.0.Beta_111417_Win64) and loaded the 3 models @chrisdembia listed above; none opened cleanly. Error reports follow.

### Models\SoccerKick\SoccerKickingModel.osim
soccerkickingmodel
<pre>
Updating Model file from 30000 to latest format...
Model name 'Soccer Ball Kicking Model' contains whitespace. It was renamed 'SoccerBallKickingModel'.
Loaded model SoccerBallKickingModel from file C:\Users\tkuchida\opensim-models\Models\SoccerKick\SoccerKickingModel.osim
Model 'SoccerBallKickingModel' has subcomponents with duplicate name 'ground'.
The duplicate is being renamed to 'ground_0'.
Model 'SoccerBallKickingModel' has subcomponents with duplicate name 'ball'.
The duplicate is being renamed to 'ball_0'.
Body 'tibia_r' not connected by a Joint.
A FreeJoint will be added to connect it to ground.
</pre>

### Models\BouncingBlock\bouncing_block.osim
<pre>
Updating Model file from 20303 to latest format...
Loaded model toy_with_forces from file C:\Users\tkuchida\opensim-models\Models\BouncingBlock\bouncing_block.osim
Visualizer couldn't open big_block_centered.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\big_block_centered.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't open linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't open linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)
</pre>

### Models\BouncingBlock\bouncing_block_weak_spring.osim
<pre>
Updating Model file from 20303 to latest format...
Loaded model toy_with_forces from file C:\Users\tkuchida\opensim-models\Models\BouncingBlock\bouncing_block_weak_spring.osim
Visualizer couldn't open big_block_centered.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\big_block_centered.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't open linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)

Visualizer couldn't open linkage1.vtp because:
SimTK Exception thrown at PolygonalMesh.cpp:411:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Attempt to load a VTK PolyData (.vtp) file from file name 'Geometry\linkage1.vtp' failed with message:
  SimTK Exception thrown at PolygonalMesh.cpp:340:
  Error detected by Simbody method PolygonalMesh::loadVtpFile(): Only format="ascii" is supported for .vtp file DataArray elements, got format="appended" for Points DataArray.
  (Required condition 'pointData.getRequiredAttributeValue("format") == "ascii"' was not met.)

  (Required condition '!"failed"' was not met.)
</pre>

**Comment by aymanhab** [comment]
@tkuchida the latest build doesn't have the conversion from binary to ascii vtp files. To tets this you either have to point the GUI to use the models branch with the fix to replace the files or wait for a later build that includes the update.  Earlier these would cause nothing to show up but was fixed by @chrisdembia to bypass which is less severe.  The soccer model issue is legit and is open as #41 separately, it's an API issue and would be great to transfer to opensim-core repo.

**Comment by tkuchida** [comment]
@aymanhab I've moved opensim-org/opensim-models/issues/41 to opensim-core, as requested. How do I "point the GUI to use the models branch with the fix to replace the files"? I cloned the models repo and pulled this branch. Do I need to enter that directory in the "Geometry Path" property?

**Comment by aymanhab** [comment]
Yes @tkuchida that would be my suggestion. Sorry that wasn't clear in my earlier comment.

**Comment by tkuchida** [comment]
Upon editing the "Geometry Path" property in the GUI, SoccerKickingModel.osim still didn't open (as expected). The two "block" models opened successfully.

bouncing_block

The "Geometry Path" issue has already been filed (https://github.com/opensim-org/opensim-gui/issues/440) and is unrelated to this PR. Merging.

**Comment by chrisdembia** [comment]
Thanks @tkuchida .

**Pull request merged**
