### PR TITLE
adjust splines left vastus intermedius to be consistent with right side

### PR DESCRIPTION
**Pull request by antoinefalisse**
@jimmyDunne, @aymanhab, @aseth1 

This PR addresses the asymmetry in gait2392 (#96) by adjusting the splines of the left vastus intermedius to be the same as the splines of the right vastus intermedius. I assumed the splines of the right side to be the correct ones as they are the same as in gait2354 and gait2354 has the same splines for both sides.

Issue #96 also reported asymmetry in the range of motion of the ankle ([-90 90] and [-60 60] for the right and left sides, respectively). It is also the case for the mtp ([-90 90] and [-60 60] for the right and left sides, respectively). I observe the same in gait2354. I can correct this in this PR if you want to but please let me know which values I should used. 

Thanks

### CODE REVIEW

**Comment by jimmyDunne** [comment]
@antoinefalisse, awesome! We are just finalizing the package for the 4.0 release, so I will merge this first thing after that.

**Comment by jimmyDunne** [comment]
@antoinefalisse, if you can update the ankle and mtp ranges of motion to 90 degrees, that would be great. 

If you intend to do that I can accept this PR now since there are a bunch of other PRs going in as well :)

**Comment by antoinefalisse** [comment]
@jimmyDunne, I adjusted the left ankle and mtp ranges of motion for the gait2392 models, gait2354 models, gait1018 models, and Hamner model. Not sure if there are still other models for which we should do that.

**Comment by jimmyDunne** [comment]
These changes look great! Thanks, Antoine, for contributing your time!

**Pull request merged**
