### PR TITLE
Put all RajagopalLaiUhlrich2023 publications into one element

### PR DESCRIPTION
**Pull request by mrrezaie**
`RajagopalLaiUhlrich2023` model has three publications in separate elements. When re-saving the model, only the first publication remains and the two others would be removed from XML file. Here I just put them into one element (separated by `|`).

### CODE REVIEW

**Comment by aymanhab** [comment]
Thanks for reporting. 
The <Model> object has a single string property for '<publications>' and single string property for '<credits>' so it's unable to maintain a list. of either In the past some authors worked around that by formatting using newlines, however this formatting is typically lost upon parsing the XML.

**Comment by nickbianco** [comment]
I think I would prefer formatting like this:

```xml
<!--Credits (e.g., model author names) associated with the model.-->
<credits>
	Rajagopal et al. (2016), Lai et al. (2017), Uhlrich et al. (2022).
	Notes: P. van den Bos changed the fiber-damping from 0.01 to default of 0.1 as suggested in M. Millard (2013) "Flexing Computational Muscle: Modeling and Simulation of Musculotendon Dynamics".
</credits>
<!--Publications and references associated with the model.-->
<publications>
	[1] Rajagopal, A., Dembia, C.L., DeMers, M.S., Delp, D.D., Hicks, J.L., Delp, S.L. (2016) Full-body musculoskeletal model for muscle-driven simulation of human gait. IEEE Transactions on Biomedical Engineering.
	[2] Lai, A.K.M., Arnold, A.S., Wakeling, J.M. (2017) Why are antagonist muscles co-activated in my simulation? A musculoskeletal model for analysing human locomotor tasks. Annals of Biomedical Engineering.
	[3] Uhlrich, S.D., Jackson, R.W., Seth, A., Kolesar, J.A., Delp, S.L. (2022) Muscle coordination retraining inspired by musculoskeletal simulations reduces knee contact force. Scientific Reports.
</publications>
```

The `<publications>` list is formatted similar to a bibliography, but is still parseable after the file is resaved. And for `<credits>`, a period before "Notes" should suffice.

I know the formatting in both elements will change upon resaving, but I think it is nice to have a more readable format in the default file like this.

**Comment by mrrezaie** [comment]
Just two further suggestions:

1. use full citation, including volume, issue, page number, and DOI:
```
Rajagopal, A., Dembia, C. L., DeMers, M. S., Delp, D. D., Hicks, J. L., & Delp, S. L. (2016). Full-Body Musculoskeletal Model for Muscle-Driven Simulation of Human Gait. IEEE transactions on bio-medical engineering, 63(10), 2068–2079. https://doi.org/10.1109/TBME.2016.2586891
Lai, A. K. M., Arnold, A. S., & Wakeling, J. M. (2017). Why are Antagonist Muscles Co-activated in My Simulation? A Musculoskeletal Model for Analysing Human Locomotor Tasks. Annals of biomedical engineering, 45(12), 2762–2774. https://doi.org/10.1007/s10439-017-1920-7
Uhlrich, S. D., Jackson, R. W., Seth, A., Kolesar, J. A., & Delp, S. L. (2022). Muscle coordination retraining inspired by musculoskeletal simulations reduces knee contact force. Scientific reports, 12(1), 9842. https://doi.org/10.1038/s41598-022-13386-9
Millard, M., Uchida, T., Seth, A., & Delp, S. L. (2013). Flexing computational muscle: modeling and simulation of musculotendon dynamics. Journal of biomechanical engineering, 135(2), 021005. https://doi.org/10.1115/1.4023390
```
2. rename the model to `RajagopalLaiUhlrich2024`

I can add more commits regarding these formats and wrist coordinates, if you want.

**Comment by nickbianco** [comment]
1. I think the abbreviated formats for the citations are fine. They are already informative enough, and adding more text would make the XML cluttered.
2. I'm fine either way for renaming or not renaming.

@mrrezaie, sorry if I stepped on your toes, but I already created #169 which includes some of the formatting changes (since I already had written them in my local model file to write my comment above). Perhaps we can include all the changes in that PR, if that's okay with you. Feel free to leave a review if you'd like.

**Comment by mrrezaie** [comment]
No worries, I'm closing this PR.

**Pull request closed without merging**
