### PR TITLE
add Rajagopal model

### PR DESCRIPTION
**Pull request by jimmyDunne**
Added the Rajagopal 2015 model

### CODE REVIEW

**Comment by tkuchida** [comment]
Based on [this recent Forum post](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=8605), don't we need to add the geometry as well?

**Comment by aseth1** [comment]
@apoorvar does your model use new bone geometry files? If so we have to include them.
If they represent essentially the same Geometry but with a different origin frame, we should consider using offset frame(s) to shift the geometry and reuse existing geometry files.

**Comment by aseth1** [comment]
thanks @apoorvar that's good to know!

**Comment by aseth1** [comment]
@apoorvar if you have a more recent model that limits the use or `CustomJoint`s (per #45) could you update this PR with it? Also include your latest Geometry folder. Thank you.

**Comment by apoorvar** [comment]
I don't have a more recent version of my model than what I shared a few years ago. I'm attaching the Geometry folder here.
[Geometry.zip](https://github.com/opensim-org/opensim-models/files/1674997/Geometry.zip)

**Comment by aseth1** [comment]
Thanks @apoorvar. Are you OK with us updating your model to replacing the `CustomJoint`s at the hips, back, and shoulders with equivalent `GimbalJoint`s? We would also rename `acromial_` to `glenohumeral_` to make it clear it isn't the acromioclavicular joint.

**Comment by apoorvar** [comment]
sounds good to me!

**Comment by chrisdembia** [comment]
I think we should be careful about updating that model. @aseth1 are you sure that changing the joints as you describe will not affect numerical results? I think we should have a versioning system where we these changes are published and the community is notified.

**Comment by aseth1** [comment]
@chrisdembia I agree. The exact model described in the paper should remain accessible on SimTK. We should be clear what modifications were made. I also OK with adding a versioning number to the name so it should be clear that the model is not identical to the 2015 publication.

**Comment by apoorvar** [comment]
It's pretty easy to have versions of the model accessible on simtk.org, so I think we should be ok on that front. We could also keep track of updates in the <Notes> section of the .osim file.

________________________________________

**Comment by aseth1** [comment]
@jimmyDunne we should include the Geometry with this repo. I would also like to see this model used built-in joint types instead of `CustomJoint`s, especially in the distributed model. Let's start with getting the model in as is with the associated Geometry folder. We can worry about streamlining it after the workshop.

**Comment by jimmyDunne** [comment]
I am going to only include the original model and pipeline files so that the Rajagopal model can have automated testing. We will add an augmented version of the model, with ball and pin joints, in a separate PR.

**Comment by aseth1** [comment]
@tkuchida I agree with adding the Geometry folder (I had a similar request Mar 4). Ideally it would be a *Geometry* folder with just those mesh files that are necessary for this model (e.g. not a Geometry folder from the OpenSim distribution).  I think that would be the cleanest solution.

**Comment by jimmyDunne** [comment]
@aseth1, if you are happy with the geometry, I can merge?

**Comment by aseth1** [comment]
Are all other geometry for the model generic and included in the `Geometry` folder distributed with OpenSim?

**Comment by jimmyDunne** [comment]
> Are all other geometry for the model generic and included in the Geometry folder distributed with OpenSim?

@aseth1, yes.

**Pull request merged**
