### PR TITLE
Hamner spline

### PR DESCRIPTION
**Pull request by antoinefalisse**
@carmichaelong, @aymanhab (not sure who is dealing with that)

In #98, I corrected the spline of the left vastus intermedius to make is consistent with the right side for the gait2392 model. I realize that it is also wrong for the Hamner model. This PR fixes this.

Thanks.

### CODE REVIEW

**Comment by carmichaelong** [comment]
Thanks @antoinefalisse! This is super helpful. I just had one comment:

I did a double check by diffing the two muscles. Unrelated to your changes, there's still a
discrepancy between the moving path points `vas_int_r-P4` and `vas_int_l-P4`. I'm not sure which one is "correct" since all 3 values' magnitudes differ.

**Comment by antoinefalisse** [comment]
I think the `location` of the moving path point is not used, cause the real location is given by the splines. Or am I wrong? At least plotting moment arms and muscle-tendon lengths gives the same for right and left after correcting the splines.
Moment_arms
Lengths

**Comment by carmichaelong** [comment]
@antoinefalisse Your logic makes sense to me that if a spline exists, then a fixed location for the path point would likely be ignored? I wonder if we can remove the `location` tag then, or if it needs to be filled regardless. @aymanhab do you know how the logic works for `MovingPathPoint`?

**Comment by carmichaelong** [comment]
A quick scan through the `MovingPathPoint` makes it seem like it ignores the `location` property that it inherits from the `Point` class.

**Comment by aymanhab** [comment]
Indeed, Location property is ignored for moving path point, its presence is a side-effect of the class inheritance but it is of no use.

**Comment by carmichaelong** [comment]
Thanks for the catch and the fix, @antoinefalisse! I'm going to merge this as is, and I started an issue on opensim-core about the `location` property not being used for `MovingPathPoint`.

**Pull request merged**
