### PR TITLE
Tibia edits

### PR DESCRIPTION
**Pull request by jimmyDunne**
(i) Deleted extraneous tibia geometry
(ii) Corrected the left and right tibia geometry
(iii) Updated gait models to use correct geometry

### CODE REVIEW

**Comment by jimmyDunne** [comment]
addresses #2 and (some of) #73

**Comment by jimmyDunne** [comment]
Screen Grab of Gait2392 with the updated tibia_r.vtp and tibia_l.vtp

screen shot 2018-05-15 at 6 00 18 pm

**Comment by jimmyDunne** [comment]
@tkuchida, could you have a quick look to give me the 👍 then I will merge.

**Comment by tkuchida** [comment]
Sorry, I didn't get to it last night. I will try to review today or tomorrow.

**Comment by tkuchida** [comment]
Ready for re-review?

**Comment by jimmyDunne** [comment]
Yes, please. The models you identified as having backwards tibias have been addressed. Thanks.

**Pull request merged**
