### PR TITLE
Add tutorial html files and supporting images

### PR DESCRIPTION
**Pull request by aymanhab**
Add Tutorial pdf files, install them to eventually have GUI point to them when off-line.

### CODE REVIEW

**Comment by jenhicks** [comment]
@aymanhab We will need to update the pdfs before the release.

**Comment by aymanhab** [comment]
Can I get quick review from @chrisdembia or @jimmyDunne

**Comment by aymanhab** [comment]
@chrisdembia On windows we used to and will continue to place tutorial files in a top level doc folder under installation. Not sure how that works on osx or if there would be permissions issues or if the layout is different. Thoughts?

**Comment by chrisdembia** [comment]
Based on this PR, these files will end up in the resources folder. I think that's where these files belong.

**Comment by aymanhab** [comment]
@chrisdembia based on this PR and https://github.com/opensim-org/opensim-models/pull/84
The files end up in a doc folder under top level install directory and the code was adjusted to find and open the files accordingly. I haven't tested on osx since I don't have access to an osx machine anymore. 
The tutorials are fixed files rather than user modifiable, so being part of the install structure seems appropriate.  Appreciate your thoughts, feedback and/or any testing you can do.

**Comment by jimmyDunne** [comment]
I assume that Chris is referring to the Resources Directory found under OpenSim.app in the install? 

On MacOS, it seems the full path would be _OpenSIm/OpenSim.app/Contents/Resources/sOpenSim/sdk/docs_. In my install, I currently have BuildOpenSimPluginSteps.pdf and the API html pages there. That folder location (Resources/sdk/docs) seems like a resonable place to copy the tutorial PDFs.

**Comment by aymanhab** [comment]
@jimmyDunne The files need to be located relative to the install directory (shown as OpenSim Home or InstallDir) on the about dialog.
On windows the path to Tutorials now is doc/*.pdf for Doxygen sdk/doc/OpenSimAPI.html
What do you see on Mac?

**Comment by jimmyDunne** [comment]
/OpenSim acd865f-2018-07-03/OpenSim acd865f-2018-07-03.app/Contents/Resources/OpenSim/sdk/doc

**Pull request merged**
