### PR TITLE
Rename leg39.osim to Leg39.osim

### PR DESCRIPTION
**Pull request by idhamari**
Solving a Linux conflict issue comes from cmake as it looks for Leg39.osim not leg39.osim

### CODE REVIEW

**Comment by jimmyDunne** [comment]
Why change the model name over the Cmake list?

**Comment by idhamari** [comment]
I didn't check the cmake file, I was not sure if it has the file name listed. It seems the models filenames are not consistant sometimes they start with small letter and sometimes with large letter. It would be nice for windows developers to put in mind this would make a problem for non-Windows users.

**Comment by jimmyDunne** [comment]
Agreed, I was looking at the model names you are correct, there isn't consistency in capitalization of the model names. My issue is here is that there are other files that reference this model, [here](https://github.com/opensim-org/opensim-models/blob/3372dd3da26239b4ad703757327f19ce69d6fc42/Pipelines/Leg39/leg39_swing_IK_Setup.xml) and [here](https://github.com/opensim-org/opensim-models/blob/3372dd3da26239b4ad703757327f19ce69d6fc42/Pipelines/Leg39/leg39_swing_short_IK_Setup.xml), so those must get updated too.

**Comment by idhamari** [comment]
done!

**Pull request closed without merging**
