### PR TITLE
Update some models to make them appear above the floor.

### PR DESCRIPTION
**Pull request by jimmyDunne**

### CODE REVIEW

**Comment by aymanhab** [comment]
@jimmyDunne will redo as XML edit so we can diff

**Comment by tkuchida** [comment]
Attempted to help @jimmyDunne with the double-pendulum. Downloaded OpenSim-4.0.Beta_110817_Win64, pulled the latest models repo, and opened Models\Pendulum\double_pendulum.osim but the model doesn't appear in the Visualizer Window. I get the floor but no model.

**Comment by aymanhab** [comment]
Any error message in the shell? Can you open the browser separately using the URL localhost:8002/threejs/editor/index.html

**Comment by tkuchida** [comment]
> Any error message in the shell?

:turtle: No error message in the Messages window, no red circle error.

> Can you open the browser separately using the URL localhost:8002/threejs/editor/index.html

Same thing, except much jerkier movement when rotating the floor.

**Comment by aymanhab** [comment]
Suggests somebody messed up the model, maybe 😃 Can you open it in a previous install if you have it? Could it be that we 're enforcing more strict naming now..

**Comment by tkuchida** [comment]
The GUI wasn't finding the Geometry directory; filed at https://github.com/opensim-org/opensim-gui/issues/440.

**Comment by aymanhab** [comment]
@jimmyDunne @tkuchida Is this ready to merge? If not how can we move it along? Thanks

**Comment by tkuchida** [comment]
I think James was going to update to avoid changing thousands of lines.

**Comment by aymanhab** [comment]
@jimmyDunne If you can't do that by tomorrow please let me know and I'll do it. If these models are in 3.3 format it could be easier if you can do the changes in 3.3 GUI.

**Comment by tkuchida** [comment]
@aymanhab I think James is away this week. I will do this tonight.

**Comment by tkuchida** [comment]
I can't open gait2354_with_pat_lig.osim and therefore can't resolve the diff issue. Also haven't figured out how to remove that file from the commit. I'll close this PR and open a new one.

**Comment by tkuchida** [comment]
To clarify: (1) The "gait2354_with_pat_lig.osim" models opens in 3.3 but not in 4.0 (OpenSim-4.0.Beta_110817_Win64). (2) Unlike the other gait models, the pelvis is located 93 cm above the floor. Thus, from (1) and (2): I don't think this model is "planted" 🌱 but I haven't verified.

**Pull request closed without merging**
