### PR TITLE
update joint reaction loads tutorial

### PR DESCRIPTION
**Pull request by carmichaelong**
@aymanhab 

- Removes kinematics for external loads
- Updates many setup files to 4.2
- Re-ran static optimization and joint reaction analysis for 4.2, updated reference
- Clean up some unnecessary files

Comparison of hip contact force results:
image

### CODE REVIEW

**Comment by aymanhab** [comment]
@carmichaelong can you remove AppState.xml it doesn't belong in the repo

**Review by aymanhab — CHANGES_REQUESTED** [review]
Remove spurious file, otherwise plot looks good

**Comment by carmichaelong** [comment]
@aymanhab I think that file should already be removed. Check out the folder on this branch here: https://github.com/opensim-org/opensim-models/tree/joint_reaction_tutorial_update/Tutorials/Estimating_Joint_Reaction_Loads

**Review by aymanhab — APPROVED** [review]
LGTM Thanks @carmichaelong

**Comment by aymanhab** [comment]
Thanks Carmichael, yes I thought it was a new file rather than a deleted
file.

Cheers,
-Ayman

**Comment by carmichaelong** [comment]
No worries. I think it's a little silly how close a large diff looks like a deleted file in Github's "Files changed" tab... makes it hard to tell which it is

**Pull request merged**
