### PR TITLE
modifying Leg39.osim 

### PR DESCRIPTION
**Pull request by idhamari**

### CODE REVIEW

**Comment by tkuchida** [comment]
Why the rename? Most of the other model filenames seem to begin with a lowercase letter.

**Comment by idhamari** [comment]
When you build the GUI in Linux it can not find the file because it look for Leg39.osim not leg39.osim

**Comment by jenhicks** [comment]
Why is this just a problem for leg39? Why is the Linux GUI looking for a file name with a capital letter?

**Comment by idhamari** [comment]
I just described what happened. The problem is gone when I changed the filename.  Probably it can be solved by modifying the CMakeLists.txt file but I think it is much better to have the naming consistency to make the software cross-platform friendly.

**Comment by jimmyDunne** [comment]
@idhamari 

Per discussion with dev team; we reverted changes to model names and we ask that you rather make changes to Cmake files.

**Comment by idhamari** [comment]
no problem!

**Pull request merged**
