### PR TITLE
Tug of war: move activation_time_constant property.

### PR DESCRIPTION
**Pull request by chrisdembia**

### CODE REVIEW

**Comment by chrisdembia** [comment]
This PR moves the `activation_time_constant` and `deactivation_time_constant` properties to the appropriate location, given changes in 4.0.

The old location is ignored when loading the file.

**Comment by aymanhab** [comment]
@chrisdembia This PR is 8 month old, did you have a chance to test it then? Any possible downstream effects in examples or documentation? Thank you

**Comment by carmichaelong** [comment]
@aymanhab I double checked the tug of war documentation, and I don't think any changes are needed (there's already a note about this issue in OpenSim 4.0 and 4.1 on the page). I also checked that changing values for the time constant in the new file does indeed affect the loaded parameter values (while the previously distributed file would "ignore" these changes due to the problematic XML location).

**Comment by aymanhab** [comment]
Thanks @carmichaelong

**Pull request merged**
