### PR TITLE
Update colab tutorials

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
Applied Carmichael's changes and removed outputs from cells.

### CODE REVIEW

**Comment by aymanhab** [comment]
Hi @AlbertoCasasOrtiz github can't understand/handle ipynb so diffing is pretty useless. If you send the link to @carmichaelong and he can run the notebooks then this should be good since it addresses his feedback. Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@carmichaelong, The notebooks with the changes are here:
https://drive.google.com/drive/folders/1xZrKRtddfYKiH365MH3nYrG_KgpjNB-w?usp=share_link

**Comment by AlbertoCasasOrtiz** [comment]
@carmichaelong I have just applied the fix for #155, and tested the six tutorials. Looks like everything is working fine now.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz How do I review this when githab diffs are messed up? @carmichaelong how did you review these earlier? Thank you

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab The most updated version of the tutorials is always available in this link: https://drive.google.com/drive/folders/1xZrKRtddfYKiH365MH3nYrG_KgpjNB-w?usp=share_link

When I update the tutorials on GitHub, I just downloaded them from that link and push them.

Another option that I use is this chrome extension, which allow opening colab notebooks stored on GitHub automatically in Google colab: https://github.com/googlecolab/open_in_colab

**Comment by aymanhab** [comment]
I tried the first two tutorials and they both looked good, I just found a couple things lacking (maybe because as insiders we tend to think it's obvious).

1. An embedded picture or animated gif of at least the first model would help make the example more concrete for a new user (I think) since there's no visualization yet. Maybe we can enlist other help if needed,
2. There's no introduction to what the "state" is or what it contains before it's used, a blurb from our documentation may be useful. 
3. For the second example I'm curious why we include both matplotlib and seaborn, can we pick one and stick with it?

Sorry if these were discussed and resolved earlier during the PR, I just think first impressions are important and if we're using this as intro to OpenSim we'd probably go the extra mile to make it super clear.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I agree with your three points. I will try to add an animated gif to the first tutorial and explain what the state is.

Regarding the second example, I introduced both matplotlib and seaborn since they are the most used visualization libraries in python. However, I agree introducing both may be confusing and makes the tutorial longer. Since Seaborn is easier to use, should we stick with Seaborn?

**Comment by aymanhab** [comment]
Thanks @AlbertoCasasOrtiz much appreciated 👍 
I don't know off hand what is commonly used now, and I do like the seaborn figures much better but I'd defer to more heavy python users @nickbianco @antoinefalisse or @gattia (thanks and sorry to pull you guys here )

**Comment by gattia** [comment]
No worries about pulling in. I don't think you can go wrong in either case. If the goal was to teach python & opensim, then I would probably say matplotlib (seaborn is based on matplotlib, so understanding matplotlib is helpful). If the goal is just for opensim, then I think the seaborn code is more straightforward and as you point out it typically looks better out of the box.

**Comment by aymanhab** [comment]
Here's an svg for the pendulum to give some visual feedback on what's the pendulum/naming-convention
pendulum2

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I added your suggestions to the notebooks in the last commit. Thank you.

**Comment by aymanhab** [comment]
Thanks, will take final pass and let you know. Would be also good for @carmichaelong to make sure all his changes are included as well.

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz Considering the feedback we got and the fact that many of our users have extensive Matlab experience, I'd lean to stay with matplotlib.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I think that's a good idea, I am going to switch to matplotlib on all of the tutorials then.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I have just switched the plotting library to matplotlib in every tutorial.

**Comment by aymanhab** [comment]
First tutorial looks good modulo a minor language change that we can update together, otherwise looks good. Thanks @AlbertoCasasOrtiz

**Comment by AlbertoCasasOrtiz** [comment]
@carmichaelong @aymanhab I was thinking on how to make the access to the tutorials easier and I have just added a readme file to the tutorials folder that allows to open them on one click, without relying on my stanford drive account. The resources are still being accessed through my account, maybe we should move them to some OpenSim drive account, or download directly the resources stored on GitHub, so we can update everything easier if changes are needed?

https://github.com/opensim-org/opensim-models/tree/update_colab_tutorials/notebooks

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab, I have just applied the comments you added to the first tutorial.

**Comment by carmichaelong** [comment]
I'm in the same boat that fresh eyes would likely be more useful than mine at this point. The main thing was to make sure that the downloading issue was fixed, which seemed to be the case when I just tested Tutorial 3. LGTM

**Pull request merged**
